env: "dev"

cluster: "openi-test"

common:
  mysql: 
    host: '192.168.202.73'
    port: 3308
    user: "root"
    pwd: "root"
  dockerRegistry:
    host: "192.168.202.74"
    port: "5000"
    user: "admin"
    pwd: "harboradmin"
  prometheus: "http://192.168.202.73:9091"

restServer:
  jwtSecret: "helloworld"
  serverPort: 9186
  logService: "/log-service"
  volumes:
    - name: ghome
      mountPath: /ghome
      hostPath: /ghome
    - name: gmodel
      mountPath: /gmodel
      hostPath: /gmodel  
    - name: kube-config
      mountPath: /kube
      hostPath: /home/amax/.kube
  k8sApiServer:
    host: "https://192.168.202.71:6443"
    kubeConfigPath: "/kube/config"
  

imageFactory:
  shield:
    port: 9001
  agent:
    port: 9002
    shield: "http://192.168.202.71:9001" 
    volumes: 
      - name: docker-run
        mountPath: /var/run
        hostPath: /var/run
      - name: docker
        mountPath: /var/lib/docker
        hostPath: /var/lib/docker

logService:
  bee:
    port: 9003
    containers: "/var/lib/docker/containers"
    volumes:
      - name: "container"
        mountPath: "/var/lib/docker/containers"
        hostPath: "/var/lib/docker/containers"
  queen:
    port: 9004
    restServer:
      host: "http://192.168.202.71:9186"
      user: "test123"
      pwd: "123456"