apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webportal
  namespace: kube-system
  labels:
    app: webportal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webportal
    spec:
      nodeSelector:
        webportal: "true"
      containers:
        - image: 192.168.202.74:5000/openi/webportal
          imagePullPolicy: Always
          name: webportal
          # env:
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 2
              memory: 2Gi
          ports:
            - name: webportal
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webportal-svc
  namespace: kube-system
  labels:
    app: webportal
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webportal
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webportal-ingress
  namespace: kube-system
spec:
  rules:
  - http:
      paths:
      - path: /openi
        backend:
          serviceName: webportal-svc
          servicePort: 8080
      - path: /
        backend:
          serviceName: webportal-svc
          servicePort: 8080
